
version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./DockerFile
    volumes:
      - .:/usr/src/app/server
    image: "backend"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./client
      dockerfile: ./DockerFile
    volumes:
      - .:/usr/src/app/client
    image: "frontend"
    ports:
      - "3000:3000"
    links:
      - "server:be"