
version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./DockerFile
    volumes:
      - .:/usr/src/app/server
    image: "xflasar/bdo-grind-tracker-backend"
    ports:
      - "3001:3001"
    restart: always
    
  frontend:
    build:
      context: ./client
      dockerfile: ./DockerFile
    volumes:
      - .:/usr/src/app/client
    image: "xflasar/bdo-grind-tracker-frontend"
    depends_on:
      - "server"
    ports:
      - "3000:3000"
    links:
      - "server:be"